import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/** Dashboard — master prompt §31. */
import { useEffect, useState } from "react";
import { api } from "../lib/api";
import { useStore } from "../store";
export function Dashboard() {
    const setView = useStore((s) => s.setView);
    const [health, setHealth] = useState(null);
    useEffect(() => {
        api.health().then(setHealth).catch(() => setHealth(null));
    }, []);
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-semibold", children: "Good morning" }), _jsx("p", { className: "text-zinc-400 mt-1", children: "What would you like me to automate?" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-3", children: [_jsxs("button", { onClick: () => setView("ai-agent"), className: "bg-zinc-800 hover:bg-zinc-700 rounded-lg p-4 text-left border border-zinc-700", children: [_jsx("div", { className: "text-sm text-zinc-400", children: "Quick Action" }), _jsx("div", { className: "mt-1 font-medium", children: "Ask AI to automate something" })] }), _jsxs("button", { onClick: () => setView("workflows"), className: "bg-zinc-800 hover:bg-zinc-700 rounded-lg p-4 text-left border border-zinc-700", children: [_jsx("div", { className: "text-sm text-zinc-400", children: "Quick Action" }), _jsx("div", { className: "mt-1 font-medium", children: "Run a Workflow" })] }), _jsxs("button", { onClick: () => setView("recorder"), className: "bg-zinc-800 hover:bg-zinc-700 rounded-lg p-4 text-left border border-zinc-700", children: [_jsx("div", { className: "text-sm text-zinc-400", children: "Quick Action" }), _jsx("div", { className: "mt-1 font-medium", children: "Record a Task" })] }), _jsxs("button", { onClick: () => setView("browser"), className: "bg-zinc-800 hover:bg-zinc-700 rounded-lg p-4 text-left border border-zinc-700", children: [_jsx("div", { className: "text-sm text-zinc-400", children: "Quick Action" }), _jsx("div", { className: "mt-1 font-medium", children: "Browser Task" })] })] }), _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-3", children: [_jsx(StatCard, { label: "Tasks Today", value: "\u2014" }), _jsx(StatCard, { label: "Successful", value: "\u2014" }), _jsx(StatCard, { label: "Failed", value: "\u2014" }), _jsx(StatCard, { label: "Running", value: "\u2014" })] }), _jsxs("div", { className: "bg-zinc-900 rounded-lg border border-zinc-800 p-4", children: [_jsx("div", { className: "text-sm text-zinc-400", children: "Service Status" }), health ? (_jsxs("div", { className: "mt-2 grid grid-cols-2 gap-2 text-sm", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-zinc-500", children: "Status" }), _jsx("span", { className: "text-emerald-400", children: health.status })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-zinc-500", children: "Mock Mode" }), _jsx("span", { className: health.mock_mode ? "text-amber-400" : "text-emerald-400", children: health.mock_mode ? "ON (safe)" : "OFF (real)" })] })] })) : (_jsx("div", { className: "mt-2 text-sm text-red-400", children: "Service unreachable" }))] })] }));
}
function StatCard({ label, value }) {
    return (_jsxs("div", { className: "bg-zinc-900 rounded-lg border border-zinc-800 p-4", children: [_jsx("div", { className: "text-xs uppercase tracking-wider text-zinc-500", children: label }), _jsx("div", { className: "mt-2 text-2xl font-semibold", children: value })] }));
}
