"""Alembic script.py.mako template."""
"""initial schema

Revision ID: f1ad71875719
Revises: 
Create Date: 2026-09-17 17:11:16.731918
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ad71875719'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OtpStore', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('OtpStore_phone_key'))

    op.drop_table('OtpStore')
    with op.batch_alter_table('DepositAccount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('DepositAccount_isActive_idx'))

    op.drop_table('DepositAccount')
    with op.batch_alter_table('Admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Admin_passwordHash_idx'))
        batch_op.drop_index(batch_op.f('Admin_username_key'))

    op.drop_table('Admin')
    with op.batch_alter_table('Installment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Installment_dueDate_idx'))
        batch_op.drop_index(batch_op.f('Installment_loanId_status_idx'))
        batch_op.drop_index(batch_op.f('Installment_updatedAt_idx'))

    op.drop_table('Installment')
    with op.batch_alter_table('ActivityLog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ActivityLog_createdAt_idx'))

    op.drop_table('ActivityLog')
    with op.batch_alter_table('Video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Video_active_sortOrder_idx'))

    op.drop_table('Video')
    op.drop_table('Setting')
    with op.batch_alter_table('Kyc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Kyc_kycStatus_idx'))
        batch_op.drop_index(batch_op.f('Kyc_kycStatus_updatedAt_idx'))
        batch_op.drop_index(batch_op.f('Kyc_userId_key'))

    op.drop_table('Kyc')
    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Notification_createdAt_idx'))
        batch_op.drop_index(batch_op.f('Notification_userId_read_idx'))

    op.drop_table('Notification')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('User_blocked_idx'))
        batch_op.drop_index(batch_op.f('User_createdAt_idx'))
        batch_op.drop_index(batch_op.f('User_otp_idx'))
        batch_op.drop_index(batch_op.f('User_phone_key'))
        batch_op.drop_index(batch_op.f('User_referralCode_key'))

    op.drop_table('User')
    with op.batch_alter_table('Loan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Loan_createdAt_idx'))
        batch_op.drop_index(batch_op.f('Loan_downpaymentStatus_createdAt_idx'))
        batch_op.drop_index(batch_op.f('Loan_downpaymentStatus_idx'))
        batch_op.drop_index(batch_op.f('Loan_status_idx'))
        batch_op.drop_index(batch_op.f('Loan_updatedAt_idx'))
        batch_op.drop_index(batch_op.f('Loan_userId_idx'))

    op.drop_table('Loan')
    with op.batch_alter_table('StaffRole', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('StaffRole_name_key'))

    op.drop_table('StaffRole')
    with op.batch_alter_table('Staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Staff_passwordHash_idx'))
        batch_op.drop_index(batch_op.f('Staff_username_key'))

    op.drop_table('Staff')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Staff',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('passwordHash', sa.TEXT(), nullable=False),
    sa.Column('blocked', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('roleId', sa.TEXT(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['StaffRole.id'], name=op.f('Staff_roleId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Staff_username_key'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('Staff_passwordHash_idx'), ['passwordHash'], unique=False)

    op.create_table('StaffRole',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('canUsers', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('canPayments', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('canLoans', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('canWithdrawals', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('canKyc', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('StaffRole', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('StaffRole_name_key'), ['name'], unique=1)

    op.create_table('Loan',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('userId', sa.TEXT(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('termDays', sa.INTEGER(), server_default=sa.text('(30)'), nullable=False),
    sa.Column('weeklyInstallment', sa.INTEGER(), nullable=False),
    sa.Column('totalInstallments', sa.INTEGER(), server_default=sa.text('4'), nullable=False),
    sa.Column('interestRate', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('withdrawalMethod', sa.TEXT(), nullable=True),
    sa.Column('withdrawalAccountTitle', sa.TEXT(), nullable=True),
    sa.Column('withdrawalAccountNumber', sa.TEXT(), nullable=True),
    sa.Column('withdrawalBank', sa.TEXT(), nullable=True),
    sa.Column('downpaymentAmount', sa.INTEGER(), nullable=True),
    sa.Column('downpaymentStatus', sa.TEXT(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('downpaymentProof', sa.TEXT(), nullable=True),
    sa.Column('downpaymentUploadedAt', sa.DATETIME(), nullable=True),
    sa.Column('downpaymentReviewedAt', sa.DATETIME(), nullable=True),
    sa.Column('downpaymentAdminNote', sa.TEXT(), nullable=True),
    sa.Column('referredCode', sa.TEXT(), nullable=True),
    sa.Column('firstInstallmentPaid', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('firstInstallmentPaidAt', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('withdrawalUnlocked', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('withdrawnAmount', sa.INTEGER(), nullable=True),
    sa.Column('withdrawnAt', sa.DATETIME(), nullable=True),
    sa.Column('withdrawalStatus', sa.TEXT(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('withdrawalTxnId', sa.TEXT(), nullable=True),
    sa.Column('withdrawalReviewedAt', sa.DATETIME(), nullable=True),
    sa.Column('withdrawalAdminNote', sa.TEXT(), nullable=True),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Loan_userId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Loan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Loan_userId_idx'), ['userId'], unique=False)
        batch_op.create_index(batch_op.f('Loan_updatedAt_idx'), ['updatedAt'], unique=False)
        batch_op.create_index(batch_op.f('Loan_status_idx'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('Loan_downpaymentStatus_idx'), ['downpaymentStatus'], unique=False)
        batch_op.create_index(batch_op.f('Loan_downpaymentStatus_createdAt_idx'), ['downpaymentStatus', 'createdAt'], unique=False)
        batch_op.create_index(batch_op.f('Loan_createdAt_idx'), ['createdAt'], unique=False)

    op.create_table('User',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('phone', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('otp', sa.TEXT(), nullable=True),
    sa.Column('otpExpiresAt', sa.DATETIME(), nullable=True),
    sa.Column('blocked', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('referralCode', sa.TEXT(), nullable=True),
    sa.Column('referredBy', sa.TEXT(), nullable=True),
    sa.Column('rewardBalance', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('User_referralCode_key'), ['referralCode'], unique=1)
        batch_op.create_index(batch_op.f('User_phone_key'), ['phone'], unique=1)
        batch_op.create_index(batch_op.f('User_otp_idx'), ['otp'], unique=False)
        batch_op.create_index(batch_op.f('User_createdAt_idx'), ['createdAt'], unique=False)
        batch_op.create_index(batch_op.f('User_blocked_idx'), ['blocked'], unique=False)

    op.create_table('Notification',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('userId', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('read', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Notification_userId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Notification_userId_read_idx'), ['userId', 'read'], unique=False)
        batch_op.create_index(batch_op.f('Notification_createdAt_idx'), ['createdAt'], unique=False)

    op.create_table('Kyc',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('userId', sa.TEXT(), nullable=False),
    sa.Column('fullName', sa.TEXT(), nullable=False),
    sa.Column('cnic', sa.TEXT(), nullable=False),
    sa.Column('fatherName', sa.TEXT(), nullable=True),
    sa.Column('dob', sa.TEXT(), nullable=True),
    sa.Column('education', sa.TEXT(), nullable=True),
    sa.Column('maritalStatus', sa.TEXT(), nullable=True),
    sa.Column('gender', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('occupation', sa.TEXT(), nullable=False),
    sa.Column('monthlyIncome', sa.INTEGER(), nullable=False),
    sa.Column('employerName', sa.TEXT(), nullable=True),
    sa.Column('hasExistingLoan', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('existingLoanAmount', sa.INTEGER(), nullable=True),
    sa.Column('existingLoanSource', sa.TEXT(), nullable=True),
    sa.Column('referenceName', sa.TEXT(), nullable=True),
    sa.Column('referencePhone', sa.TEXT(), nullable=True),
    sa.Column('referenceRelation', sa.TEXT(), nullable=True),
    sa.Column('cnicFrontImage', sa.TEXT(), nullable=True),
    sa.Column('cnicBackImage', sa.TEXT(), nullable=True),
    sa.Column('selfieImage', sa.TEXT(), nullable=True),
    sa.Column('kycStatus', sa.TEXT(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('kycReviewedAt', sa.DATETIME(), nullable=True),
    sa.Column('kycAdminNote', sa.TEXT(), nullable=True),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Kyc_userId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Kyc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Kyc_userId_key'), ['userId'], unique=1)
        batch_op.create_index(batch_op.f('Kyc_kycStatus_updatedAt_idx'), ['kycStatus', 'updatedAt'], unique=False)
        batch_op.create_index(batch_op.f('Kyc_kycStatus_idx'), ['kycStatus'], unique=False)

    op.create_table('Setting',
    sa.Column('key', sa.TEXT(), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('Video',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('subtitle', sa.TEXT(), nullable=True),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('sortOrder', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Video_active_sortOrder_idx'), ['active', 'sortOrder'], unique=False)

    op.create_table('ActivityLog',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('actor', sa.TEXT(), nullable=False),
    sa.Column('action', sa.TEXT(), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('userId', sa.TEXT(), nullable=True),
    sa.Column('loanId', sa.TEXT(), nullable=True),
    sa.Column('ip', sa.TEXT(), nullable=True),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ActivityLog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ActivityLog_createdAt_idx'), ['createdAt'], unique=False)

    op.create_table('Installment',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('loanId', sa.TEXT(), nullable=False),
    sa.Column('installmentNumber', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('dueDate', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('paidAt', sa.DATETIME(), nullable=True),
    sa.Column('proofImage', sa.TEXT(), nullable=True),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['loanId'], ['Loan.id'], name=op.f('Installment_loanId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Installment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Installment_updatedAt_idx'), ['updatedAt'], unique=False)
        batch_op.create_index(batch_op.f('Installment_loanId_status_idx'), ['loanId', 'status'], unique=False)
        batch_op.create_index(batch_op.f('Installment_dueDate_idx'), ['dueDate'], unique=False)

    op.create_table('Admin',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('passwordHash', sa.TEXT(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Admin_username_key'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('Admin_passwordHash_idx'), ['passwordHash'], unique=False)

    op.create_table('DepositAccount',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('method', sa.TEXT(), nullable=False),
    sa.Column('accountTitle', sa.TEXT(), nullable=False),
    sa.Column('accountNumber', sa.TEXT(), nullable=False),
    sa.Column('color', sa.TEXT(), server_default=sa.text("'#00A651'"), nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('sortOrder', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('DepositAccount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('DepositAccount_isActive_idx'), ['isActive'], unique=False)

    op.create_table('OtpStore',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('phone', sa.TEXT(), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.Column('expiresAt', sa.DATETIME(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('OtpStore', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('OtpStore_phone_key'), ['phone'], unique=1)

    # ### end Alembic commands ###
